FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir poetry

COPY pyproject.toml /app/pyproject.toml
COPY poetry.lock /app/poetry.lock

RUN poetry config virtualenvs.create false \
  && poetry install --only load-testing --no-root

COPY load_tests/ /app/load_tests/

EXPOSE 8089

ENTRYPOINT ["locust", "-f", "load_tests/locustfile.py"]
