# Generated by Django 5.0.3 on 2025-02-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
