# Generated by Django 5.0.3 on 2024-03-28 12:44

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=255, unique=True),
        ),
    ]
