# Generated by Django 5.0.3 on 2025-02-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contracttype",
            old_name="contract_type",
            new_name="name",
        ),
    ]
