# Generated by Django 5.0.3 on 2025-02-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_alter_city_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='JobApp.city'),
            preserve_default=False,
        ),
    ]
