# Generated by Django 5.0.3 on 2025-02-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0002_rename_contract_type_contracttype_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remotenesslevel",
            old_name="remote_type",
            new_name="name",
        ),
    ]
