# Generated by Django 5.0.3 on 2024-03-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
