# Generated by Django 5.0.3 on 2025-02-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_city_country_remove_employerlocation_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
    ]
