# Generated by Django 5.0.3 on 2024-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0003_user_is_candidate_user_is_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='website_url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
