# Generated by Django 5.0.3 on 2025-02-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0003_rename_remote_type_remotenesslevel_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seniority",
            old_name="seniority_level",
            new_name="name",
        ),
    ]
