# Generated by Django 5.0.3 on 2025-02-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0003_rename_country_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
    ]
