# Generated by Django 5.0.3 on 2025-07-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0008_benefit_alter_candidateeducation_is_current_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_candidate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_employer",
        ),
    ]
