# Generated by Django 5.0.3 on 2024-07-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0008_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
