# Generated by Django 5.0.3 on 2025-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0010_alter_joboffer_contract_alter_joboffer_remoteness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(upload_to="resumes/"),
        ),
    ]
