# Generated by Django 5.0.3 on 2025-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0011_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='contract',
            field=models.CharField(choices=[('employment_contract', 'Employment contract'), ('mandate_contract', 'Mandate contract'), ('b2b_contract', 'B2B contract'), ('specific_task_contract', 'Specific task contract'), ('internship_contract', 'Internship contract')], max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='remoteness',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='seniority',
            field=models.CharField(choices=[('INTERN', 'Intern'), ('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior'), ('LEAD', 'Lead')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
