# Generated by Django 5.0.3 on 2025-08-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0012_alter_joboffer_contract_alter_joboffer_remoteness_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offerresponse",
            unique_together={("offer", "candidate")},
        ),
    ]
