# Generated by Django 5.0.3 on 2025-09-19 18:41

import django.core.validators
from django.db import migrations, models

import JobApp.models


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0013_alter_offerresponse_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=JobApp.models.Candidate.resume_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
