# Generated by Django 5.0.3 on 2025-09-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0014_alter_candidate_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="website_url",
            field=models.URLField(blank=True, max_length=255, unique=True),
        ),
    ]
