# Generated by Django 5.0.3 on 2025-09-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0015_alter_employer_website_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employer",
            name="benefits",
        ),
        migrations.CreateModel(
            name="EmployerBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="JobApp.benefit"
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JobApp.employer",
                    ),
                ),
            ],
        ),
    ]
