# Generated by Django 5.0.3 on 2025-09-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0016_remove_employer_benefits_employerbenefit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
    ]
