# Generated by Django 5.0.3 on 2025-09-22 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0017_alter_employer_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
