# Generated by Django 5.0.3 on 2025-09-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0018_joboffer_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joboffer",
            name="skills",
        ),
    ]
