# Generated by Django 5.0.3 on 2025-10-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JobApp", "0019_remove_joboffer_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="seniority",
            field=models.CharField(
                choices=[
                    ("INTERN", "Intern"),
                    ("JUNIOR", "Junior"),
                    ("REGULAR", "Regular/Mid"),
                    ("SENIOR", "Senior"),
                    ("LEAD", "Lead"),
                ],
                max_length=255,
            ),
        ),
    ]
